services:
  react:
    container_name: react_app
    image: react_app
    build:
      context: ./MGWebPro-FE
    volumes:
      - ./MGWebPro-FE:/app
      - /app/node_modules
    ports:
      - "5173:5173"

  django:
    image: django_app
    container_name: django_app
    build:
      context: ./MGWebPro-BE
    ports:
      - "8000:8000"
    volumes:
      - ./MGWebPro-BE:/app
    command: [ "./wait-for-it.sh", "-t", "30", "mysql:3306", "--", "python", "manage.py", "runserver", "0.0.0.0:8000" ]
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=store-db
    volumes:
      - django_react_data:/data/db
      - ./dumps:/docker-entrypoint-initdb.d:ro

volumes:
  django_react_data:
